syntax on
set number
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256
set tabstop=8
set softtabstop=8
set shiftwidth=8
set noexpandtab
set smartindent
set autoindent
